# Generated by Django 2.2 on 2019-04-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('auth', models.CharField(max_length=20)),
                ('press', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Borrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('book_id', models.CharField(max_length=20)),
                ('date_borrow', models.DateTimeField(auto_now_add=True)),
                ('date_return', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('college', models.CharField(blank=True, max_length=20, null=True)),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
