# Generated by Django 2.2 on 2019-04-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_borrows_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='hotpic')),
                ('index', models.SmallIntegerField(max_length=20)),
            ],
        ),
    ]
